FROM golang:latest

RUN go get  github.com/uudashr/gopkgs/v2/cmd/gopkgs     \
            github.com/ramya-rao-a/go-outline           \
            github.com/cweill/gotests/gotests           \
            github.com/fatih/gomodifytags               \
            github.com/haya14busa/goplay/cmd/goplay     \
            github.com/go-delve/delve/cmd/dlv@master    \
            honnef.co/go/tools/cmd/staticcheck          \
            golang.org/x/tools/gopls                    \
            golang.org/x/tools/godoc